version: '3'

services:
  telebot:
    image: telebot:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ct_TB_app
    hostname: telebot
    restart: always
    # links:
    #   - mongodb
    ports:
      - 6014:1406
    command: sh -c "/wait && /telebot/telebotserver"
    environment:
      MONGO_HOST: mongodb #${MONGO_HOST}
      MONGO_DB_NAME: telebot
      TELEGRAM_TOKEN: xxxxxxx
      GIN_MODE: release
      APP_PORT: 1406

      # WAIT_HOSTS: postgres:5432, mysql:3306, mongo:27017
      WAIT_HOSTS: mongodb:27017, redis:6379
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30

    depends_on:
      - mongodb
      - mongoclient
      - redis

  mongodb:
    image: mongo:latest
    container_name: ct_TB_mongodb
    hostname: mongo
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 17027:27017
      # - 27017:27017
      # - 27018:27018
      # - 27019:27019
    command: mongod --logpath=/dev/null

  redis:
    image: redis:alpine
    container_name: ct_TB_redis
    hostname: redis
    ports:
      - 7963:6379

  mongoclient:
    image: mongoclient/mongoclient
    container_name: ct_TB_mongoclient
    hostname: mongoclient
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 2020:3000
    # links:
    #   - mongodb
