version: '3'

services:
  database:
    image: mongo:latest
    container_name: ct_telebot_db
    hostname: telebot-db
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - 17027:27017
    command: mongod --logpath=/dev/null

  telebot:
    image: telebot:latest
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: ct_telebot_app
    hostname: telebot-app
    restart: always
    depends_on:
      - database
    links:
      - database
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      MONGO_HOST: database #${MONGO_HOST}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      GIN_MODE: ${GIN_MODE}
      APP_PORT: ${APP_PORT}

  mongoclient:
    image: mongoclient/mongoclient
    container_name: ct_mongoclient
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 2020:3000
    links:
      - database
